#!/usr/bin/env python3
import os
import glob
import subprocess

# Loop through all .ui files in the widgets folder
for widget_file in glob.glob("./widgets/*.ui"):
    python_file = f"{widget_file[:-3]}.py"

    # Remove the old .py file
    if os.path.exists(python_file):
        os.remove(python_file)

    # Run pyside6-uic to generate a new .py file
    subprocess.run(["pyside6-uic", widget_file, "-o", python_file])
