#!/usr/bin/env python3
import os
import sys

from PySide6 import QtWidgets
from PySide6.QtUiTools import QUiLoader

loader = QUiLoader()


def mainwindow_setup(widget):
    widget.setWindowTitle("Carrierade")


app = QtWidgets.QApplication(sys.argv)

# Find the base directory of the script
base_dir = os.path.dirname(__file__)
widget_dir = os.path.join(base_dir, "..", "widgets")

# Load the UI file that's passed in as an argument
if len(sys.argv) < 2:
    ui_file = os.path.join(widget_dir, "MainWindow.ui")
else:
    ui_file = os.path.join(widget_dir, sys.argv[1])

ui = loader.load(ui_file)

# Setup the main window and show it
mainwindow_setup(ui)
ui.show()
app.exec()
